server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:clients
    username: sa
    password:
    driverClassName: org.h2.Driver
card:
  getcards:
    url: "http://localhost:8082/api/v1/cards"