server:
  port: 8761
application:
  name: service-discovery
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-with-eureka: true
    fetch-registry: true