server:
  port: 8082
application:
  name: ms-card-service
spring:
  datasource:
     driver-class-name: org.postgresql.Driver
     password: 'postgres'
     username: 'postgres'
     url: jdbc:postgresql://localhost:5432/card-database-postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true
      hibernate.show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-with-eureka: false
    fetch-registry: false